name: Swift

on: [push, pull_request]

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test 2>&1 | xcpretty -c
